### ISSUE TITLE
docker build failure 

### ISSUE THREAD

**Issue by svkamp** [Faithlife/sdc-portal#10]
docker build sdc-portal/
Sending build context to Docker daemon 4.015 MB
Step 1 : FROM node:0.10.31
 ---> 1837e7508c9b
Step 2 : EXPOSE 8080
 ---> Using cache
 ---> 7a73108fcd8f
Step 3 : COPY . /src
 ---> Using cache
 ---> 235014483673
Step 4 : WORKDIR /src
 ---> Using cache
 ---> b1f98e019e86
Step 5 : RUN npm install --unsafe-perm
 ---> Running in bd5e9c8e14d5
npm ERR! Error: Attempt to unlock express@4.9.3, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.5.7-200.fc23.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /src
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! Error: Attempt to unlock faye-websocket@0.9.4, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.5.7-200.fc23.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /src
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! Error: Attempt to unlock grunt-eslint@11.0.0, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.5.7-200.fc23.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /src
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! Error: Attempt to unlock iso-bunyan-stream@1.0.0, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.5.7-200.fc23.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /src
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! Error: Attempt to unlock littlest-isomorph@0.10.5, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.5.7-200.fc23.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /src
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /src/npm-debug.log
npm ERR! not ok code 0
The command '/bin/sh -c npm install --unsafe-perm' returned a non-zero code: 1

**Comment by stensonb** [comment]
I was able to complete the "docker build..." just now...maybe you have a broken npm or docker?

```
22:13 $ npm version
{ http_parser: '1.0',
  node: '0.10.18',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.15',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.3.8',
  'sdc-portal': '0.0.0' }
```

```
22:12 $ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64
```

**Comment by svkamp** [comment]
welp, ill recheck that i did get it to build on CentOS 7 with npm and node, now just have to figure out how to configure it with my deployed SDC .... config docs are a bit sparse for being new to this.

**Comment by stensonb** [comment]
I got it built, but I will say, I don't have the node server working correctly...it's throwing 500s for the static assets...looking around now...

**Comment by svkamp** [comment]
looking like this? same here i think, here my config

cat /root/.sdcportalrc 
/*
 * The auth provider in this example has been commented out.
 * You will default to full access "AdminParty" non-auth.
 * If you want to use the sample OAuth configuration you can setup a developer
 * account and obtain a consumer key and secret at https://developer.faithlife.com
 *
 * IMPORTANT: Remove or replace any commented out lines in this file.
 */
{
/*  "auth": {
    "provider": "oauth",
    "requestTokenUrl": "https://auth.logos.com/oauth/v1/initiate",
    "authorizeUrl": "https://auth.logos.com/oauth/v1/authorize",
    "accessTokenUrl": "https://auth.logos.com/oauth/v1/token",
    "consumerKey": "<your-consumer-key-here>",
    "consumerSecret": "<your-consumer-secret-here>",
    "developerInfoUrl": "https://auth.logos.com/oauth/v1/users/current?setAlias=true",
    "developerIdKey": "userId", //userId will differ if not using auth.logos.com
    "developerNameKey": "alias", //alias will differ if not using auth.logos.com
    "developers": {
      // Map of developer ID to available SDC logins:
      "123456789": ["Core", "API"],
      "912356777": ["API"],
      "222000333": ["Core"]
    },
    "session": {
      "secret": "<unique-string-here>"
    }
  },*/
  "sdc" : {
    "dataCenters": {
      "us-east": {
        "cloudapiUrl": "https://162.217.150.74"
      },
    },
    "users": {
      "admin": {
        "key": "/Users/sdcportal/admin_rsa", "keyId": "coal-1 sdc key", "login": "admin"
      },
      "Dingo": {
        "key": "/Users/sdcportal/admin_rsa", "81a85ade-6099-eb0c-xxxsecurity-editxxx": "us-east", "login": "dingo"
      }
    }
  }
}


Running "less:client" (less) task
File public/bundle.css created: 0 B → 20.94 kB

Running "watch" task
Completed in 3.271s at Sun Jun 26 2016 05:50:33 GMT+0000 (UTC) - Waiting...
sdc-portal 05:50:34| info: Initializing AuthProvider: admin-party
Config: {"env":"development","hostname":"portal.optimcloud.com","port":8080,"cluster":{"instances":2},"logger":{"format":"dev"},"auth":{"provider":"admin-party","session":{"secret":"shhh"}},"client":{"portal":{"proxy":{"rootUrl":"/api"},"actual":{"rootUrl":"http://portal.optimcloud.com:8080/api"}}},"sdc":{},"/*":true,"* The auth provider in this example has been commented out.":true,"* You will default to full access \"AdminParty\" non-auth.":true,"* If you want to use the sample OAuth configuration you can setup a developer":true,"* account and obtain a consumer key and secret at https://developer.faithlife.com":true,"*":true,"* IMPORTANT: Remove or replace any commented out lines in this file.":true,"*/":true,"{":true,"/*  \"auth\": {":true,"\"provider\": \"oauth\",":true,"\"requestTokenUrl\": \"https://auth.logos.com/oauth/v1/initiate\",":true,"\"authorizeUrl\": \"https://auth.logos.com/oauth/v1/authorize\",":true,"\"accessTokenUrl\": \"https://auth.logos.com/oauth/v1/token\",":true,"\"consumerKey\": \"<your-consumer-key-here>\",":true,"\"consumerSecret\": \"<your-consumer-secret-here>\",":true,"\"developerInfoUrl\": \"https://auth.logos.com/oauth/v1/users/current?setAlias":"true\",","\"developerIdKey\": \"userId\", //userId will differ if not using auth.logos.com":true,"\"developerNameKey\": \"alias\", //alias will differ if not using auth.logos.com":true,"\"developers\": {":true,"// Map of developer ID to available SDC logins:":true,"\"123456789\": [\"Core\", \"API\"],":true,"\"912356777\": [\"API\"],":true,"\"222000333\": [\"Core\"]":true,"},":true,"\"session\": {":true,"\"secret\": \"<unique-string-here>\"":true,"}":true,"},*/":true,"\"sdc\" : {":true,"\"dataCenters\": {":true,"\"us-east\": {":true,"\"cloudapiUrl\": \"https://162.217.150.74\"":true,"\"users\": {":true,"\"admin\": {":true,"\"key\": \"/Users/sdcportal/admin_rsa\", \"keyId\": \"coal-1 sdc key\", \"login\": \"admin\"":true,"\"Dingo\": {":true,"\"key\": \"/Users/sdcportal/admin_rsa\", \"81a85ade-6099-eb0c-80a6-a4b01b4c400b\": \"us-east\", \"login\": \"dingo\"":true,"_":[],"configs":["/root/.sdcportalrc"],"config":"/root/.sdcportalrc"}
sdc-portal 05:50:34| info: Server 49504 listening at 162.217.150.80:8080...
sdc-portal 05:50:45| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 05:50:45| info: < GET http://portal.optimcloud.com:8080/api/datacenters
sdc-portal 05:50:45| info: GET / 200 40.151 ms - 3709
sdc-portal 05:50:45| info: GET /api/datacenters 500 7.776 ms - 970
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /root/sdc-portal/lib/server/api.js:67:29
    at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)
    at next (/root/sdc-portal/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/root/sdc-portal/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)
    at /root/sdc-portal/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/root/sdc-portal/node_modules/express/lib/router/index.js:312:12)
    at /root/sdc-portal/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/root/sdc-portal/node_modules/express/lib/router/index.js:295:3)
sdc-portal 05:50:45| info: > GET http://portal.optimcloud.com:8080/api/datacenters 500 25.000 ms
sdc-portal 05:50:45| info: D dataCenter:dataCenters:get:failed { [InternalServerErrorError: TypeError: Object.keys called on non-object<br> &nbsp; &nbsp;at Function.keys (native)<br> &nbsp; &nbsp;at /root/sdc-portal/lib/server/api.js:67:29<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)<br> &nbsp; &nbsp;at next (/root/sdc-portal/node_modules/express/lib/router/route.js:100:13)<br> &nbsp; &nbsp;at Route.dispatch (/root/sdc-portal/node_modules/express/lib/router/route.js:81:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)<br> &nbsp; &nbsp;at /root/sdc-portal/node_modules/express/lib/router/index.js:234:24<br> &nbsp; &nbsp;at Function.proto.process_params (/root/sdc-portal/node_modules/express/lib/router/index.js:312:12)<br> &nbsp; &nbsp;at /root/sdc-portal/node_modules/express/lib/router/index.js:228:12<br> &nbsp; &nbsp;at Function.match_layer (/root/sdc-portal/node_modules/express/lib/router/index.js:295:3)
]
  code: 500,
  name: 'InternalServerErrorError',
  response: 
   { domain: null,
     _events: {},
     _maxListeners: 10,
     res: 
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '',
        method: null,
        statusCode: 500,
        client: [Object],
        _consuming: true,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        req: [Object],
        text: 'TypeError: Object.keys called on non-object<br> &nbsp; &nbsp;at Function.keys (native)<br> &nbsp; &nbsp;at /root/sdc-portal/lib/server/api.js:67:29<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)<br> &nbsp; &nbsp;at next (/root/sdc-portal/node_modules/express/lib/router/route.js:100:13)<br> &nbsp; &nbsp;at Route.dispatch (/root/sdc-portal/node_modules/express/lib/router/route.js:81:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/sdc-portal/node_modules/express/lib/router/layer.js:76:5)<br> &nbsp; &nbsp;at /root/sdc-portal/node_modules/express/lib/router/index.js:234:24<br> &nbsp; &nbsp;at Function.proto.process_params (/root/sdc-portal/node_modules/express/lib/router/index.js:312:12)<br> &nbsp; &nbsp;at /root/sdc-portal/node_modules/express/lib/router/index.js:228:12<br> &nbsp; &nbsp;at Function.match_layer (/root/sdc-portal/node_modules/express/lib/router/index.js:295:3)\n',
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function],
        body: undefined },
     request: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _agent: false,
        _formData: null,
        method: 'GET',
        url: 'http://portal.optimcloud.com:8080/api/datacenters',
        header: {},
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        _redirectList: [],
        req: [Object],
        protocol: 'http:',
        host: 'portal.optimcloud.com:8080',
        _timeout: 0,
        then: [Function: then],
        _callback: [Function: noop],
        _timer: [Object],
        res: [Object],
        response: [Circular],
        called: true },
     req: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _headerSent: true,
        _header: 'GET /api/datacenters HTTP/1.1\r\nhost: 162.217.150.80:8080\r\naccept-encoding: gzip, deflate, sdch\r\nuser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36\r\nif-none-match: W/"8+X8c3POm9npns5zRmUb8g=="\r\naccept-language: en-GB,en-US;q=0.8,en;q=0.6\r\ndnt: 1\r\naccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nupgrade-insecure-requests: 1\r\nconnection: keep-alive\r\n\r\n',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        socket: [Object],
        connection: [Object],
        agent: false,
        socketPath: undefined,
        method: 'GET',
        path: '/api/datacenters',
        _headers: [Object],
        _headerNames: [Object],
        parser: null,
        res: [Object] },
     links: {},

**Comment by stensonb** [comment]
yes...same issue...having trouble with the /api/datacenters endpoint...

**Comment by stensonb** [comment]
haha...so, I got past the /api/datacenters error...turns out, my config was invalid json, and the parser was barfing silently...(causing config.sdc.dataCenters to be null)

today's lesson: validate your json

**Comment by svkamp** [comment]
sounds good.... and you said its dockerized? so is it useable for you?

**Comment by stensonb** [comment]
not working yet...docker builds, but the app is useless as it's still missing static assets:  https://github.com/Faithlife/sdc-portal/issues/11

**Comment by svkamp** [comment]
want to flip me an edited version of your config i can try it on my dc with just grunt without dockerisms

**Comment by stensonb** [comment]
I literally took the .sdcportalrc.example file and removed all comments, including the comment at the head of the file...json doesn't like comments...ever.

**Comment by stensonb** [comment]
it goes without saying that the config i'm using doesn't "work" yet...my details are not in the config (nor have I found great docs on how the various auth providers should work)...i'll probably just follow along in the code to see what it does...

and then write a PR for more docs here. :)
