### ISSUE TITLE
static asset missing

### ISSUE THREAD

**Issue by stensonb** [Faithlife/sdc-portal#11]
Repro -

```
git clone https://github.com/Faithlife/sdc-portal.git
(remove commented section from .sdcportalrc.example)
cp .sdcportalrc.example .sdcportalrc
docker build -t sdc-portal .
docker run -d sdc-portal
```

then open a browser to the container IP:8080, and notice all static assets are missing... :(

![screen shot 2016-06-28 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/933389/16434476/f46616b6-3d44-11e6-94f6-3d2eafe3c72f.png)

**Comment by stensonb** [comment]
Here's the logs from the node server (not the exact logs from the screenshot, but same affect):

```
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:09:59| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:09:59| info: GET / 200 9.417 ms - 3710
sdc-portal 23:09:59| info: GET /api/datacenters 200 1.228 ms - 29
sdc-portal 23:09:59| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 4.000 ms
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:09:59| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:09:59| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:09:59| info: GET /bundle.css 500 4.501 ms - 1149
TypeError: Cannot read property 'params' of undefined
    at React.createClass.componentWillMount (/src/lib/components/app.jsx:22:25)
    at chainedFunction [as componentWillMount] (/src/node_modules/react/lib/ReactCompositeComponent.js:666:9)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:792:14)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at /src/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/src/node_modules/react/lib/Transaction.js:134:20)
sdc-portal 23:09:59| info: GET /dependencies.bundle.js 500 4.567 ms - 1149
TypeError: Cannot read property 'params' of undefined
    at React.createClass.componentWillMount (/src/lib/components/app.jsx:22:25)
    at chainedFunction [as componentWillMount] (/src/node_modules/react/lib/ReactCompositeComponent.js:666:9)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:792:14)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at /src/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/src/node_modules/react/lib/Transaction.js:134:20)
sdc-portal 23:09:59| info: GET /api/datacenters 200 1.128 ms - 29
sdc-portal 23:09:59| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 5.000 ms
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:09:59| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:09:59| info: GET /favicon.ico 304 1.751 ms - -
sdc-portal 23:09:59| info: GET /app.bundle.js 500 3.681 ms - 1149
TypeError: Cannot read property 'params' of undefined
    at React.createClass.componentWillMount (/src/lib/components/app.jsx:22:25)
    at chainedFunction [as componentWillMount] (/src/node_modules/react/lib/ReactCompositeComponent.js:666:9)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:792:14)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at /src/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/src/node_modules/react/lib/Transaction.js:134:20)
sdc-portal 23:09:59| info: GET /api/datacenters 200 0.644 ms - 29
sdc-portal 23:09:59| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 9.000 ms
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
sdc-portal 23:09:59| info: GET /api/datacenters 200 1.006 ms - 29
sdc-portal 23:09:59| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 5.000 ms
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:09:59| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:09:59| info: GET /dependencies.bundle.js 500 5.086 ms - 1149
TypeError: Cannot read property 'params' of undefined
    at React.createClass.componentWillMount (/src/lib/components/app.jsx:22:25)
    at chainedFunction [as componentWillMount] (/src/node_modules/react/lib/ReactCompositeComponent.js:666:9)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:792:14)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at /src/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/src/node_modules/react/lib/Transaction.js:134:20)
sdc-portal 23:09:59| info: GET /api/datacenters 200 0.449 ms - 29
sdc-portal 23:09:59| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 3.000 ms
sdc-portal 23:09:59| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
sdc-portal 23:10:00| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 23:10:00| info: < GET http://fd1aaefeef9e:8080/api/datacenters
sdc-portal 23:10:00| info: GET /app.bundle.js 500 4.783 ms - 1149
TypeError: Cannot read property 'params' of undefined
    at React.createClass.componentWillMount (/src/lib/components/app.jsx:22:25)
    at chainedFunction [as componentWillMount] (/src/node_modules/react/lib/ReactCompositeComponent.js:666:9)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:792:14)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/src/node_modules/react/lib/ReactPerf.js:50:21)
    at /src/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/src/node_modules/react/lib/Transaction.js:134:20)
sdc-portal 23:10:00| info: GET /api/datacenters 200 4.313 ms - 29
sdc-portal 23:10:00| info: > GET http://fd1aaefeef9e:8080/api/datacenters 200 8.000 ms
sdc-portal 23:10:00| info: D dataCenter:dataCenters:get:succeeded [ 'us-west-1' ]
```

**Comment by stensonb** [comment]
Apparently, these are generated via "grunt"...i'll have a PR for the Dockerfile shortly once I figure out what it should look like (seems like anybody should be able to "docker build ... && docker run ..." and get it work work)

**Comment by stensonb** [comment]
Thanks @ChristianAlexander
